services:
  postgres:
    image: postgres:15-alpine
    container_name: altar-db
    environment:
      POSTGRES_USER: user_altar
      POSTGRES_PASSWORD: password_altar
      POSTGRES_DB: altar_digital
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
